### PR TITLE
Tareq branch3

### PR DESCRIPTION
**Pull request by TareqHanafi643**
The whole logic of the login and some of the sign up is there. Missing the connection from the JPA repository to the spring security for the login and sign up (to save the users in our database instead of the memory). If someone knows how to set up the application.properties, that would be a great help.

### CODE REVIEW

**Comment by TareqHanafi643** [comment]
The repositories need to be JPA repositories instead of crud repositories.

**Comment by TareqHanafi643** [comment]
We need to find a way to create a database and link it to the DataSource

**Comment by KingKuess** [comment]
Looks good, resolve the conflicts and merge!

**Review by KingKuess — APPROVED** [review]
Please merge conflicts

**Comment by nnamdiokwechime** [comment]
Were the errors here fixed? why was it merged to master?

**Pull request merged**
